[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]
ESP_LOG = "info"
ESP_HAL_CONFIG_PLACE_RMT_DRIVER_IN_RAM = "true"

[build]
target = "xtensa-esp32s3-none-elf"
rustdocflags = ["--default-theme=ayu"]
rustflags = ["-C", "link-arg=-nostartfiles"]

[unstable]
build-std = ["alloc", "core"]
